config_map:
  - name: JBOSS_A_MQ_BROKER_URL
    value: tcp://broker-amq-tcp.blockchain-demo-test.svc:61616
  - name: ETHEREUM_SERVICE_API_URL
    value: http://go-ethereum.blockchain-demo-test.svc:8545
  - name: JAEGER_SERVICE_NAME
    value: test-blockchain-gateway-ms
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.blockchain-demo-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.blockchain-demo-monitoring.svc     